#!/usr/bin/env python3
"""
Non-Root User Security Monitoring Script
Generated by Non-Root Standalone System
"""

import os
import json
import time
import logging
import subprocess
from datetime import datetime, timezone

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class SecurityMonitor:
    """Security monitoring for non-root containers."""
    
    def __init__(self):
        self.user_config = {
            'username': 'appuser',
            'uid': 1001,
            'gid': 1001
        }
        self.security_policy = {
            'drop_capabilities': ['ALL'],
            'no_new_privileges': True,
            'read_only_root_fs': True
        }
    
    def check_container_user(self, container_name):
        """Check if container is running as non-root user."""
        try:
            # Check container user
            result = subprocess.run(
                ['docker', 'exec', container_name, 'whoami'],
                capture_output=True, text=True, timeout=10
            )
            
            if result.returncode == 0:
                user = result.stdout.strip()
                if user == self.user_config['username']:
                    return {'status': 'pass', 'user': user, 'message': 'Running as non-root user'}
                else:
                    return {'status': 'fail', 'user': user, 'message': f'Running as {user}, expected {self.user_config["username"]}'}
            else:
                return {'status': 'error', 'message': f'Failed to check user: {result.stderr}'}
                
        except subprocess.TimeoutExpired:
            return {'status': 'error', 'message': 'Timeout checking container user'}
        except Exception as e:
            return {'status': 'error', 'message': f'Error: {e}'}
    
    def check_container_security(self, container_name):
        """Check container security configuration."""
        try:
            # Get container configuration
            result = subprocess.run(
                ['docker', 'inspect', container_name],
                capture_output=True, text=True, timeout=10
            )
            
            if result.returncode == 0:
                config = json.loads(result.stdout)[0]
                host_config = config.get('HostConfig', {})
                
                security_check = {
                    'container_name': container_name,
                    'user': config.get('Config', {}).get('User', 'root'),
                    'cap_drop': host_config.get('CapDrop', []),
                    'read_only': host_config.get('ReadonlyRootfs', False),
                    'security_opt': host_config.get('SecurityOpt', []),
                    'issues': []
                }
                
                # Check for security issues
                if security_check['user'] in ['root', '', '0', '0:0']:
                    security_check['issues'].append('Container running as root')
                
                if 'ALL' not in security_check['cap_drop']:
                    security_check['issues'].append('Not all capabilities dropped')
                
                if not security_check['read_only']:
                    security_check['issues'].append('Root filesystem not read-only')
                
                no_new_privileges = any('no-new-privileges:true' in opt for opt in security_check['security_opt'])
                if not no_new_privileges:
                    security_check['issues'].append('no-new-privileges not enabled')
                
                security_check['status'] = 'pass' if not security_check['issues'] else 'fail'
                return security_check
                
            else:
                return {'status': 'error', 'message': f'Failed to inspect container: {result.stderr}'}
                
        except Exception as e:
            return {'status': 'error', 'message': f'Error: {e}'}
    
    def monitor_containers(self, containers=None):
        """Monitor security of specified containers."""
        if containers is None:
            containers = ['trading-bot-secure', 'dashboard-secure', 'redis-secure']
        
        monitoring_result = {
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'containers_checked': len(containers),
            'results': {},
            'overall_status': 'unknown',
            'issues_found': 0
        }
        
        total_issues = 0
        
        for container in containers:
            logger.info(f"🔍 Checking container: {container}")
            
            # Check user
            user_check = self.check_container_user(container)
            
            # Check security configuration
            security_check = self.check_container_security(container)
            
            # Combine results
            container_result = {
                'user_check': user_check,
                'security_check': security_check,
                'overall_status': 'pass' if user_check.get('status') == 'pass' and security_check.get('status') == 'pass' else 'fail'
            }
            
            monitoring_result['results'][container] = container_result
            
            # Count issues
            if security_check.get('issues'):
                total_issues += len(security_check['issues'])
            
            # Log results
            if container_result['overall_status'] == 'pass':
                logger.info(f"✅ {container}: Security check passed")
            else:
                logger.warning(f"⚠️ {container}: Security issues found")
                if security_check.get('issues'):
                    for issue in security_check['issues']:
                        logger.warning(f"   - {issue}")
        
        monitoring_result['issues_found'] = total_issues
        monitoring_result['overall_status'] = 'pass' if total_issues == 0 else 'fail'
        
        return monitoring_result
    
    def generate_report(self, monitoring_result):
        """Generate security monitoring report."""
        report = {
            'report_type': 'non_root_security_monitoring',
            'generated_at': datetime.now(timezone.utc).isoformat(),
            'monitoring_result': monitoring_result,
            'summary': {
                'containers_checked': monitoring_result['containers_checked'],
                'overall_status': monitoring_result['overall_status'],
                'total_issues': monitoring_result['issues_found'],
                'security_score': max(0, 100 - (monitoring_result['issues_found'] * 10))
            },
            'recommendations': []
        }
        
        # Generate recommendations
        if monitoring_result['issues_found'] > 0:
            report['recommendations'].append('Review and fix container security configuration')
        
        if monitoring_result['overall_status'] == 'fail':
            report['recommendations'].append('Immediate attention required for security violations')
        
        return report

def main():
    """Main monitoring function."""
    logger.info("🔐 Starting Non-Root User Security Monitoring")
    
    monitor = SecurityMonitor()
    
    # Check if Docker is available
    try:
        subprocess.run(['docker', '--version'], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        logger.error("❌ Docker not available. Please ensure Docker is installed and running.")
        return
    
    # Monitor containers
    monitoring_result = monitor.monitor_containers()
    
    # Generate report
    report = monitor.generate_report(monitoring_result)
    
    # Save report
    report_file = f"security_monitoring_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(report_file, 'w') as f:
        json.dump(report, f, indent=2)
    
    # Print summary
    logger.info(f"📊 Security Score: {report['summary']['security_score']}/100")
    logger.info(f"📋 Report saved: {report_file}")
    
    if monitoring_result['overall_status'] == 'fail':
        logger.warning("⚠️ Security issues detected - review required")
    else:
        logger.info("✅ All security checks passed")

if __name__ == "__main__":
    main()
